version: "3.9"

services:
  db:
    image: postgres:16
    container_name: mis-eventos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mis-eventos-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALG: ${JWT_ALG}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - "8000:8000"
    command: [ "bash", "-lc", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload" ]
    volumes:
      - ./backend:/app

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mis-eventos-web
    depends_on:
      - api
    env_file:
      - ./.env
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:5173"
    command: [ "bash", "-lc", "npm run dev -- --host" ]
    volumes:
      - ./frontend:/app

volumes:
  pgdata:
